### ISSUE TITLE
UI | Responsive Issue

### ISSUE THREAD

**Issue by function0xMarki** [syscoin/syscoin-bridge#11]
With a 13" screen, the main _<div class="css-16p6cal">_ rectangle exceeds the upper menu area _<div class="css-1vwjtb2">_ with the information and buttons. Therefore, it is necessary to zoom-out to be able to see it correctly.

This means that some devices will have display issues with small screens.

https://github.com/syscoin/syscoin-bridge/assets/112655312/5653e5c9-8174-4533-b392-400dbaff6b03

The top menu should never be able to be overshadowed by any object.

Using 100% Firefox with 100% scaling
![100% Firefox 13](https://github.com/syscoin/syscoin-bridge/assets/112655312/91c1b75e-047a-4ed1-9e15-7edb4c413c11)

Using Chromium-based browsers with 100% scaling
![100% Chromium 13](https://github.com/syscoin/syscoin-bridge/assets/112655312/9eddfdd5-7612-4536-a360-3a37a09a2164)

**Comment by eskrano** [comment]
@function0xMarki  can we check it as fixed now ? I've tested but can not see nothing critical now.

**Comment by function0xMarki** [comment]
This issue keeps happening with 13" laptop screens.
With the zoom at 100% "default".

![image](https://github.com/syscoin/syscoin-bridge/assets/112655312/edc2c630-e975-47c9-b583-82dfa223c211)

**Comment by function0xMarki** [comment]
Closed due to moving to another repository.
