### ISSUE TITLE
Pre-populate NFT/Token Contract Address from URL

### ISSUE THREAD

**Issue by develCuy** [syscoin/syscoin-bridge#9]
For both the /nft and /create-token paths:

The URL parameter "contract" can be used to prepopulate its value in the corresponding box. For example:

/nft?contract=0x...

/create-token?contract=0x...

If the "redirect" parameter is also supported, it can enable integration with other dApps, such as Luxy. For instance:

/nft?contract=0x...&redirect=luxy.io/user/0x...

Once the bridge is complete, provide a button for the user to return to the original dApp.

**Comment by eskrano** [comment]
@develCuy after which action we should handle redirect for user?

**Comment by eskrano** [comment]
Done
